version: '2.1'
services:
    redis:
        image: 'redis:5.0.6'
        command: redis-server --requirepass cowbell

    postgres:
        image: postgres:9.6
        environment:
            - POSTGRES_USER=cowbell
            - POSTGRES_PASSWORD=cowbell
            - POSTGRES_DB=churnery
        # Uncomment these lines to persist data on the local filesystem.
            - PGDATA=/var/lib/postgresql/data/pgdata
        volumes:                 
            - ../../airflow-data/postgres:/var/lib/postgresql/data/pgdata
            # - ./script/initdb.sql:/docker-entrypoint-initdb.d/initdb.sql
    # uncomment initdb if you need initdb at first run 
    initdb: 
        build: . 
        entrypoint: airflow initdb 
        depends_on: 
            - postgres
    webserver:
        build: .
        restart: always
        depends_on:
            - postgres
            - redis
        environment:
            - FERNET_KEY=${AIRFLOW__CORE__FERNET_KEY}
            - EXECUTOR=Celery
            - POSTGRES_USER=cowbell
            - POSTGRES_PASSWORD=cowbell
            - POSTGRES_DB=churnery
            - REDIS_PASSWORD=cowbell
        volumes:
            - ../airflow-dags:/usr/local/airflow/dags
            # Uncomment to include custom plugins
            - ./plugins:/usr/local/airflow/plugins
        ports:
            - "8080:8080"
        command: webserver
        healthcheck:
            test: ["CMD-SHELL", "[ -f /usr/local/airflow/airflow-webserver.pid ]"]
            interval: 30s
            timeout: 30s
            retries: 3

    flower:
        build: .
        restart: always
        depends_on:
            - redis
        environment:
            - EXECUTOR=Celery
            - REDIS_PASSWORD=cowbell
        ports:
            - "5555:5555"
        command: flower

    scheduler:
        build: .
        restart: always
        depends_on:
            - webserver
        volumes:
            - ../airflow-dags:/usr/local/airflow/dags
            # Uncomment to include custom plugins
            - ./plugins:/usr/local/airflow/plugins
        environment:
            - FERNET_KEY=${AIRFLOW__CORE__FERNET_KEY}
            - EXECUTOR=Celery
            - POSTGRES_USER=cowbell
            - POSTGRES_PASSWORD=cowbell
            - POSTGRES_DB=churnery
            - REDIS_PASSWORD=cowbell
        command: scheduler
        healthcheck:
          test: ["CMD-SHELL", "[ -f /usr/local/airflow/airflow-scheduler.pid ]"]
          interval: 30s
          timeout: 30s
          retries: 3

    worker_1:
        build: .
        restart: always
        depends_on:
            - scheduler
        volumes:
            - ../airflow-dags:/usr/local/airflow/dags
            # Uncomment to include custom plugins
            - ./plugins:/usr/local/airflow/plugins
        environment:
            - FERNET_KEY=${AIRFLOW__CORE__FERNET_KEY}
            - EXECUTOR=Celery
            # - POSTGRES_USER=airflow
            # - POSTGRES_PASSWORD=airflow
            # - POSTGRES_DB=airflow
            # - REDIS_PASSWORD=redispass
        command: worker_1
        healthcheck:
          test: ["CMD-SHELL", "[ -f /usr/local/airflow/airflow-worker_1.pid ]"]
          interval: 30s
          timeout: 30s
          retries: 3

    worker_2:
        build: .
        restart: always
        depends_on:
            - scheduler
        volumes:
            - ../airflow-dags:/usr/local/airflow/dags
            # Uncomment to include custom plugins
            - ./plugins:/usr/local/airflow/plugins
        environment:
            - FERNET_KEY=${AIRFLOW__CORE__FERNET_KEY}
            - EXECUTOR=Celery
            # - POSTGRES_USER=airflow
            # - POSTGRES_PASSWORD=airflow
            # - POSTGRES_DB=airflow
            # - REDIS_PASSWORD=redispass
        command: worker_2
        healthcheck:
          test: ["CMD-SHELL", "[ -f /usr/local/airflow/airflow-worker_2.pid ]"]
          interval: 30s
          timeout: 30s
          retries: 3

